name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build library
      run: make
    - name: Build test cases
      run: make tests
    - name: Run test cases
      run: make run-tests
